name: CI-CD_practice

on:
  push:
    branch: [main]name: Production CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    
    runs-on: [self-hosted, production]

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: cp .env.example.production .env
    - name: build project
      run: CI=false npm run build
    - name: Copy the project to production directory
      run: cp -R -f /home/ubuntu/actions-runner/_work/maria_website/maria_website/build/* /var/www/html/

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v2
      - run: npm i

      # Check if the process exists; if yes, restart it, otherwise start it
      - run: |
          if pm2 list | grep -q 'index'; then
            pm2 restart index
          else
            pm2 start index.js
          fi
