name: CI-CD_practice

on:
  push:
    branch: [main]

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v2
      - run: npm i
      - run: |
          if pm2 show index.js ; then
            echo "Process is already running, restarting..."
            pm2 restart index
          else
            echo "Process is not running, starting..."
            pm2 start index.js
          fi
