name: Development_CI/CD

on:
  push:
    branch: [development_branch]

jobs:
  build:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v2
      - run: npm i

      # Check if the process exists; if yes, restart it, otherwise start it
      - run: |
          if pm2 list | grep -q 'index'; then
            pm2 restart index
          else
            pm2 start index.js
          fi
